#!/bin/sh

im $SHOP_OWNER || Forbidden

js() {
	cat <<!
`cat $ROOT/js/nfiles.js`

nfiles( 'images',
	document.getElementById('images'),
	document.getElementById('submit'),
	'`_ Submit`', 'file[]', '/e/image-add', '/e/images-edit');
!
}

case "$REQUEST_METHOD" in
	POST) ;;
	GET)
		export _TITLE="`_ $shop_id` - `_ "Add product"`"
		export __TITLE="`_ Title`"
		export _DESCRIPTION="`_ Description`"
		export _IMAGES="`_ Images`"
		export _STOCK="`_ Stock`"
		export _PRICE="`_ Price`"
		export _SUBMIT="`_ Submit`"
		export JS="`js`"

		Normal 200 shop/$shop_id/add
		Cat add
		;;
	*) NotAllowed ;;
esac

PRODUCT_ID_PATH=$SHOP_PATH/.count
PRODUCT_ID="`counter_inc $PRODUCT_ID_PATH`"
PRODUCT_PATH=$SHOP_PATH/$PRODUCT_ID
DF_USER=$SHOP_OWNER

fmkdir $PRODUCT_PATH
urldecode $title | fwrite $PRODUCT_PATH/title
urldecode $description | fwrite $PRODUCT_PATH/description
images="`nfiles $images`"
test -z "$images" || a2l $images | fwrite $PRODUCT_PATH/images
echo $price | fwrite $PRODUCT_PATH/price
echo $stock | fwrite $PRODUCT_PATH/stock

_see_other /shop/$shop_id
