#!/bin/sh

im $SHOP_OWNER || Forbidden

js() {
	cat <<!
`cat $ROOT/js/nfiles.js`

nfiles( 'images',
	document.getElementById('images'),
	document.getElementById('submit'),
	'`_ Submit`', 'file[]', '/e/image-add', '/e/images-edit');
!
}

case "$REQUEST_METHOD" in
	POST) ;;
	GET)
		export _TITLE="`_ $shop_id` - `_ "Edit product"` #$iid"
		export __TITLE="`_ Title`"
		export _DESCRIPTION="`_ Description`"
		export _IMAGES="`_ Images`"
		export _ADD_TO_STOCK="`_ "Add to stock"`"
		export _PRICE="`_ Price`"
		export _SUBMIT="`_ Submit`"
		export JS="`js`"

		product_env $iid
		export iid
		export product_stock
		export product_title
		export product_description
		export product_images
		export product_price

		Normal 200 shop/$shop_id/$iid/edit
		Cat edit
		;;
	*) NotAllowed ;;
esac

PRODUCT_PATH=$SHOP_PATH/$iid
DF_USER=$SHOP_OWNER

fmkdir $PRODUCT_PATH
urldecode $title | fwrite $PRODUCT_PATH/title
urldecode $description | fwrite $PRODUCT_PATH/description
images="`nfiles $images`"
test -z "$images" || a2l $images | fwrite $PRODUCT_PATH/images
echo $price | fwrite $PRODUCT_PATH/price

local stock_exp="`cat $PRODUCT_PATH/stock` + $stock"
local new_stock="`echo $stock_exp | bc`"
echo $new_stock | fwrite $PRODUCT_PATH/stock

_see_other /shop/$shop_id/$iid
