#!/bin/ksh

product_id=$1
PRODUCT_PATH=$SHOP_PATH/$product_id

if [[ -z "$product_id" ]] || [[ ! -d "$PRODUCT_PATH" ]]; then
	Fatal 404 Product not found
fi

shift
case "$1" in
	delete) shift; . ./delete ; exit 0 ;;
	edit) shift; . ./edit ; exit 0 ;;
esac

ProductImages() {
	while read product_image_path; do
		PImage $product_image_path | surround a "href=\"$product_image_path\""
	done
}

CartAdd() {
	if [[ $product_stock -le 0 ]]; then
		return
	fi

	cat <<!
<form action="/shop/$shop_id/cart" method="POST">
	<button class="rs ps">`_ "Add to cart"`</button>	
	<input type="hidden" name="shop_id" value="$shop_id"></input>
	<input type="hidden" name="product_id" value="$product_id"></input>
</form>
!
}

ProductDelete() {
	cat <<!
<form action="/shop/$shop_id/$product_id/delete" method="POST">
	<input type="hidden" name="shop_id" value="$shop_id"></input>
	<input type="hidden" name="product_id" value="$product_id"></input>
	<button class="rs ps c1">`_ "Delete product"`</button>
</form>
!
}

[[ "$REQUEST_METHOD" == "GET" ]] || NotAllowed

export _TITLE="`_ $shop_id` - `_ Product` #$product_id"

product_env $product_id
export product_title
export product_price
export product_stock
export PRODUCT_IMAGES="`echo "$product_images" | ProductImages | fw 8`"
export _STOCK="`_ Stock`"

if [[ "$product_stock" != "0" ]]; then
	export ADD_TO_CART="`CartAdd $CART_PATH`"
fi

if im $SHOP_OWNER; then
	export DELETE_PRODUCT="`ProductDelete $product_id`"
	export EDIT_BTN="`EditBtn "/shop/$shop_id/$product_id/edit"`"
fi

Normal 200 shop/$shop_id/$product_id
Scat template/index
