#!/bin/sh

iid=$1
poem_path=$ITEM_PATH
comments_path="$poem_path/comments.txt"

if test "$REQUEST_METHOD" == "POST"; then
	test ! -z "$REMOTE_USER" || Unauthorized
	echo $REMOTE_USER: "`urldecode "$comment"`" | fappend $comments_path
	_see_other $iid\#comments
fi

ITEM_PATH="$poem_path/pt_PT.html"

new_item_path="$poem_path/$lang.html"
test ! -f $new_item_path || ITEM_PATH=$new_item_path

cat > $DOCUMENT_ROOT/tmp/bottom <<EOF
<form action="$iid" method="post" class="h f fic">
	<input type="hidden" name="iid" value="$iid"></input>
	<input class="fg" name="comment"></input>
</form>
<pre id="comments">`cat $comments_path | revlines | no_html`</pre>
EOF

cat - > $DOCUMENT_ROOT/tmp/fun <<!
<div class='width tac cf15 tsxl'>`counter_inc $poem_path/counter.txt`</div>
<a href='#comments' class='$RB'>💬</a>
!

echo "<pre>`cat $ITEM_PATH`</pre>"
