#!/bin/sh

USER_PATH=$DOCUMENT_ROOT/users/$HTTP_PARAM_username
USER_RCODE="`cat $USER_PATH/rcode`"

if test "$HTTP_PARAM_rcode" != "$USER_RCODE"; then
	Fatal 401 "You can not do that"
fi

rm $USER_PATH/rcode
TOKEN="`rand_str_1`"
echo $HTTP_PARAM_username > $DOCUMENT_ROOT/sessions/$TOKEN
header "Set-Cookie: QSESSION=$TOKEN; SameSite=Lax"
SeeOther /
