packages:
  - items/*
  - items/*/src/*

onlyBuiltDependencies:
  - '@swc/core'
  - '@tty-pt/ndc'
  - '@tty-pt/qdb'
  - '@tty-pt/qmap'
  - '@tty-pt/qsys'
  - '@tty-pt/vim.css'
  - esbuild
  - unrs-resolver
