#!/bin/sh

if test "`uname`" = "Linux"; then
	pldd() {
		ldd $1 2>/dev/null | tail -n +2 | while read filename arrow ipath rest; do
			if test -z "$ipath"; then
				echo "$filename" | grep -q "^\/" \
					&& echo "$filename" \
					|| true
				continue
			fi
			echo "$ipath"
		done
	}
else
	pldd() {
		ldd $1 2>/dev/null | tail -n +4 | awk '{print $7}'
	}
fi


link() {
	origin=$1
	target=$2
	echo $target: $origin
}

rinstall() {
	test -e "$1" || return 0
        local line="`echo $1 | grep -q "^\/" && echo $1 | sed s/.// || echo $1`"
	local link="`readlink "$1" || true`"
	if echo "$link" | grep -q "^\/"; then
		rinstall "$link"
		local target="`echo $link | sed s/.//`"
		echo $line: $target
		echo $target > ".links/`echo $line | tr '/' '_'`"
		echo chroot-ln += $line
	elif test -z "$link"; then
		if test -d "$1"; then
			ls $1 | while read file; do rinstall "$1/$file"; done
		else
			if test -x "$1"; then
				pldd $1 | while read filename; do
					rinstall "$filename"
				done
			fi

			echo chroot-cp += $line
		fi
	else
		local target_prefix="`dirname $line`"
		rinstall "/$target_prefix/$link"
		echo $line: $target_prefix/$link
		echo $target_prefix/$link > ".links/`echo $line | tr '/' '_'`"
		echo chroot-ln += $line
	fi
}

rinstall $1
