#!/bin/sh

USER_PATH=$DOCUMENT_ROOT/users/$REMOTE_USER

Field() {
	cat | cond || {
		cat <<!
<div class="vxs">
	<div class="tsxs">$1</div>
	<pre class="cf15">`cat $contents`</pre>
</div>
!
	}
}

Address() {
	Field "$_ADDRESS" <<!
`zcat $USER_PATH/address_line_1`
`zcat $USER_PATH/address_line_2`
`zcat $USER_PATH/zip`
!
}

PhoneNumber() {
	if test ! -f "$USER_PATH/phone_number"; then
		return
	fi

	local label="`_ "Phone number"`"
	local value="`cat $USER_PATH/phone_number`"

	cat <<!
<div class="vxs">
	<div class="tsxs">$label</div>
	<a href="tel:$value" class="ts cf15">$value</a>
</div>
!

}

AccountInfo() {
	if test ! -f "$USER_PATH/iban" || test ! -f "$USER_PATH/bicswift"; then
		return
	fi

	local label="`_ "Account information"`"
	local value="`cat $USER_PATH/phone_number`"

	cat <<!
<div class="vxs tss">
	<div class="tsxs">$label</div>
	<div class="_xs">
		<span class="tsxs">`_ IBAN`</span>
		<span class="cf15">`cat $USER_PATH/iban`</span>
	</div>
	<div class="_xs">
		<span class="tsxs">`_ BICSWIFT`</span>
		<span class="cf15">`cat $USER_PATH/bicswift`</span>
	</div>
</div>
!

}

if test -z "$user_id" || im $user_id; then
	EditBtn "/e/user-edit?user_id=$user_id"
fi > $DOCUMENT_ROOT/tmp/fun

_TITLE="`_ User` - $REMOTE_USER"

export iban="`zcat $USER_PATH/iban`"
export bicswift="`zcat $USER_PATH/bicswift`"

cat <<!
<div>User: $REMOTE_USER</div>

<div class="h f fw v">
	<div class="f v">
		`zcat $USER_PATH/name | Field "$(_ Name)"`

		`Address`
	</div>
	<div class="f v">
		`PhoneNumber`

		`AccountInfo`
	</div>
</div>

<div class="tac tsxl f">
	<a class="btn" href="~$REMOTE_USER">`_ Page`</a>
</div>

<div class="tac tsxl f">
	<a class="btn" href="logout">`_ Logout`</a>
</div>
!
