#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/shop.sh

EmptyContents() {
	_EMPTY="`_ "Empty"`"
	echo "<div class=\"tsxl tac\">$_EMPTY</div>"
}

Contents() {
	TOTAL_CART_EXP="`process_cart $CART_PATH`"
	TOTAL="`echo "$TOTAL_CART_EXP" | bc -l`"
	_SUBMIT="`_ Submit`"
	PRODUCTS="`ProductsFromCart -rcart $CART_PATH`"
	PRODUCTS="`Wrap "$PRODUCTS"`"

	cat <<!
<div class="v">
	$PRODUCTS
</div>
<div class="tcv fic v">
	<div class="tsxl">$TOTAL€</div>
	<form action="/e/order" method="POST">
		<input type="hidden" name="shop_id" value="$shop_id"></input>
		<button>$_SUBMIT</Button>
	</form>
</div>
!
}

if [[ -z "$shop_id" ]] || [[ ! -d $SHOP_PATH ]]; then
	Fatal 404 Shop not found
fi

case "$REQUEST_METHOD" in
	POST)
		PRODUCT_PATH=$SHOP_PATH/$product_id
		if [[ -z "$product_id" ]] || [[ ! -d "$PRODUCT_PATH" ]]; then
			Fatal 404 Product not found
		fi

		if [[ $quantity -lt 0 ]]; then
			Fatal 400 Invalid quantity
		fi

		SHOP_OWNER="`cat $SHOP_PATH/.owner`"
		fmkdir $USER_SHOP_PATH
		STOCK="`cat $PRODUCT_PATH/stock`"
		if [[ -f $CART_PATH ]] && cat $CART_PATH | grep -q $product_id; then
			OLD_QUANTITY="`cat $CART_PATH | grep $product_id | awk '{ print $2 }'`"
		else
			OLD_QUANTITY=0
		fi
		AVAILABLE_EXP="$STOCK - ($quantity - $OLD_QUANTITY) >= 0"
		AVAILABLE="`echo $AVAILABLE_EXP | bc`"

		[[ "$AVAILABLE" != "0" ]] || Fatal 400 Not enough stock

		if [[ "$quantity" == "0" ]]; then
			sed -i "/^$product_id /d" $CART_PATH
		else
			fappend $CART_PATH echo $product_id $quantity
			cat $CART_PATH | awk \
				'{a[$1]=$2} END{for (i in a) print i FS a[i]}' \
				> $ROOT/tmp/cart
			mv $ROOT/tmp/cart $CART_PATH
		fi

		case "$return" in
			cart)
				see_other cart ?shop_id=$shop_id
				;;
			shop)
				see_other shop ?shop_id=$shop_id
				;;
			product)
				see_other product ?shop_id=$shop_id\&product_id=$product_id
				;;
			*)
				Fatal 400 "Invalid return"
				;;
		esac

		;;

	GET)
		if [[ -f "$CART_PATH" ]] && [[ ! -z `cat $CART_PATH` ]]; then
			CONTENTS="`Contents`"
		else
			CONTENTS="`EmptyContents`"
		fi
		export CONTENTS

		export _TITLE="`_ $shop_id` - `_ Cart`"

		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
