#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/shop.sh

EmptyContents() {
	_EMPTY="`_ "Empty"`"
	echo "<div class=\"tsxl tac\">$_EMPTY</div>"
}

Products() {
	local product_id
	while read product_id quantity; do
		product_env $product_id
		cat <<!
<a class="card f v8 b0 fic p" href="/e/product?shop_id=$shop_id&product_id=$product_id">
	`PImage $product_image_path`
	<div class="tsxl">$product_title</div>
	<div class="tsl">$quantity x $product_price€</div>
	`echo "$product_description" | csurround p`
</a>
!
	done
}

Contents() {
	TOTAL_CART_EXP="`process_cart $CART_PATH`"
	TOTAL="`echo "$TOTAL_CART_EXP" | bc -l`"
	_SUBMIT="`_ Submit`"
	PRODUCTS="`cat $CART_PATH | Products | fw`"

	cat <<!
$PRODUCTS

<div class="tcv fic v">
	<div class="tsxl">$TOTAL€</div>
	<form action="/e/order" method="POST">
		<input type="hidden" name="shop_id" value="$shop_id"></input>
		<button>$_SUBMIT</Button>
	</form>
</div>
!
}

if [[ -z "$shop_id" ]] || [[ ! -d $SHOP_PATH ]]; then
	Fatal 404 Shop not found
fi

case "$REQUEST_METHOD" in
	POST)
		local PRODUCT_PATH=$SHOP_PATH/$product_id

		if [[ -z "$product_id" ]] || [[ ! -d "$PRODUCT_PATH" ]]; then
			Fatal 404 Product not found
		fi

		product_env $product_id # TODO think twice about this use case

		if [[ -f $CART_PATH ]] && cat $CART_PATH | grep -q $product_id; then
			# only do something if this is not the case,
			# otherwise just redir
			echo -n ""
		elif [[ "$product_stock" != 0 ]]; then
			echo $product_id 1 | fappend $CART_PATH
		else
			Fatal 400 Not enough stock
		fi

		see_other cart-edit ?shop_id=$shop_id

		;;

	GET)
		if [[ -f "$CART_PATH" ]] && [[ ! -z `cat $CART_PATH` ]]; then
			CONTENTS="`Contents`"
			export EDIT_BTN="`EditBtn "/e/cart-edit?shop_id=$shop_id"`"

		else
			CONTENTS="`EmptyContents`"
		fi
		export CONTENTS

		export _TITLE="`_ $shop_id` - `_ Cart`"

		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
