#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/school.sh

case "$REQUEST_METHOD" in
	POST)
		school_id="`urldecode $school_id`"
		class_id="`urldecode $class_id`"
		teacher_id="`urldecode $teacher_id`"

		CLASS_PATH="$SCHOOL_PATH/classes/$class_id"

		fwrite $CLASS_PATH/.teacher echo $teacher_id

		see_other class ?school_id=$school_id\&class_id=$class_id
		;;

	GET)
		export _TITLE="`_ "Assign teacher to class"`"
		export _TEACHER_ID="`_ "Teacher ID"`"
		export _CLASS_ID="`_ "Class ID"`"
		export _SUBMIT="`_ Submit`"
		export class_id

		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
