#!/bin/ksh

. $DOCUMENT_ROOT/lib/auth.sh
. $DOCUMENT_ROOT/lib/common.sh
. $DOCUMENT_ROOT/lib/school.sh

CLASS_PATH="$SCHOOL_PATH/classes/$class_id"
teacher_id="`cat $CLASS_PATH/.teacher`"

im $SCHOOL_OWNER $teacher_id || Forbidden

case "$REQUEST_METHOD" in
	POST)
		STUDENT_PATH="$SCHOOL_PATH/students/$student_id"

		echo $class_id `urldecode $grade` | fappend $STUDENT_PATH/grades

		see_other class ?school_id=$school_id\&class_id=$class_id
		;;

	GET)
		export _TITLE="`_ "Assign grade to student"`"
		export _SUBMIT="`_ Submit`"
		export class_id
		export student_id

		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac

