#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/school.sh

Courses() {
	for_each_in "$SCHOOL_PATH/courses" classes "$class_id" \
		| SmallButtons course \&school_id=$school_id | cond || {
		echo "<h2>`_ Courses`</h2>"
		cat $contents | fw 8
	}
}

Teacher() {
	_TEACHER="`_ Teacher`"
	LabeledIDEdit "$_TEACHER" teacher $teacher_id class $class_id \&school_id=$school_id
}

AssignGrades() {
	if im $SCHOOL_OWNER $teacher_id; then
		ls $SCHOOL_PATH/students | while read student_id; do
			STUDENT_PATH=$SCHOOL_PATH/students/$student_id

			if grep -q "^$class_id " $STUDENT_PATH/grades; then
				continue
			fi

			cat $STUDENT_PATH/courses | while read course_id; do
				COURSE_PATH=$SCHOOL_PATH/courses/$course_id

				if grep -q $class_id $COURSE_PATH/classes; then
					echo $student_id
				fi
			done
		done | sort -u | while read student_id; do
			cat <<!
<a class="btn c0 ps rs" href="/e/class-grading?school_id=$school_id&class_id=$class_id&student_id=$student_id">
	$student_id
</a>
!
		done | cond || {
			echo "<h2>`_ "Assign grades"`</h2>"
			cat $contents | fw 8
		}
	fi
}

case "$REQUEST_METHOD" in
	GET)
		export class_id
		CLASS_PATH=$SCHOOL_PATH/classes/$class_id
		teacher_id="`cat $CLASS_PATH/.teacher`"
		export class_title="`cat $CLASS_PATH/title`"
		export _SEMESTER="`_ Semester`"
		export COURSES="`Courses`"
		export TEACHER="`Teacher`"
		export ASSIGN_GRADES="`AssignGrades`"
		export class_semester="`cat $CLASS_PATH/semester`"

		NormalCat ?school_id=$school_id\&class_id=$class_id

		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac


