#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh

case "$REQUEST_METHOD" in
	GET)
		export _TITLE="Commands"
		export _NEVERDARK="`_ "Never Dark"`"
		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
