#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/school.sh

case "$REQUEST_METHOD" in
	POST)
		school_id="`urldecode $school_id`"
		course_id="`urldecode $course_id`"
		teacher_id="`urldecode $teacher_id`"

		COURSE_PATH="$SCHOOL_PATH/courses/$course_id"

		fwrite $COURSE_PATH/.teacher echo $teacher_id

		see_other course ?school_id=$school_id\&course_id=$course_id
		;;

	GET)
		export _TITLE="`_ "Assign teacher to course"`"
		export _TEACHER_ID="`_ "Teacher ID"`"
		export _SUBMIT="`_ Submit`"
		export course_id

		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
