#!/bin/ksh

. $DOCUMENT_ROOT/lib/auth.sh
. $DOCUMENT_ROOT/lib/common.sh
. $DOCUMENT_ROOT/lib/school.sh

im $SCHOOL_OWNER || Forbidden

case "$REQUEST_METHOD" in
	POST)
		if invalid_id $course_id; then
			Fatal 400 Not a valid ID
		fi

		COURSE_PATH="$SCHOOL_PATH/courses/$course_id"

		fmkdir $COURSE_PATH
		echo $teacher_id | fwrite $COURSE_PATH/.teacher
		urldecode $course_title | fwrite $COURSE_PATH/title

		see_other course ?school_id=$school_id\&course_id=$course_id
		;;

	GET)
		export _TITLE="`_ "Add course to school"`"
		export _COURSE_ID="`_ "Course ID"`"
		export _COURSE_TITLE="`_ "Course Title"`"
		export _REGENT="`_ Regent`"
		export _SUBMIT="`_ Submit`"

		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
