#!/bin/ksh

. $DOCUMENT_ROOT/lib/optional-auth.sh
. $DOCUMENT_ROOT/lib/common.sh
. $DOCUMENT_ROOT/lib/school.sh

case "$REQUEST_METHOD" in
	GET)
		export _TITLE="`_ Courses`"

		if im $SCHOOL_OWNER; then
			export COURSE_ADD="<a class=\"$RB\" href=\"/e/course-add?school_id=$school_id\">+</a>"
		fi

		export COURSES="`ls $SCHOOL_PATH/courses | BigButtons course \&school_id=$school_id`"

		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
