#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/school.sh

COURSE_PATH=$SCHOOL_PATH/courses/$course_id

Classes() {
	cat $COURSE_PATH/classes | BigButtons class \&school_id=$school_id
}

case "$REQUEST_METHOD" in
	GET)
		export course_id
		export course_title="`cat $COURSE_PATH/title`"
		export _REGENT="`_ Regent`"
		export _CLASSES="`_ Classes`"
		export CLASSES="`Classes`"
		export teacher_id="`cat $COURSE_PATH/.teacher`"
		if [[ "$REMOTE_USER" == "$SCHOOL_OWNER" ]]; then
			export CLASS_ASSOCIATE="<a class=\"$RB\" href=\"/e/class-associate?school_id=$school_id&course_id=$course_id\">+</a>"
		fi

		NormalCat ?school_id=$school_id\&course_id=$course_id

		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
