#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh

Image() {
	cat <<!
<img height="128" class="ofc s_k256 b0" src="http://$HTTP_HOST/img/$1" />
!
}

Images() {
	while read line; do
		Image $line
	done
}

find_images() {
	find $1 -type f | sed "s|$1/||"
}

case "$REQUEST_METHOD" in
	GET)
		export _TITLE="`_ Images`"
		IMAGES="`find_images $ROOT/htdocs/img | Images`"
		IMAGES="`Wrap $IMAGES`"
		export IMAGES
		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac

