#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh

case "$REQUEST_METHOD" in
	POST)
		grep -q "^$REMOTE_USER$" $ROOT/.uploaders \
			|| Forbidden "You can not do that"

		USER_IMAGES_PATH=$ROOT/htdocs/img/$REMOTE_USER

		fmkdir $USER_IMAGES_PATH

		file_count="`cat $ROOT/tmp/mpfd/file-count`"
		for i in `seq 0 $file_count`; do
			FILE_PATH=$ROOT/tmp/mpfd/file$i
			fbytes $FILE_PATH
			IMAGE_ID="`counter_inc $ROOT/public/img-counter`"
			ext="`file -i $FILE_PATH | awk '{print $2}' | tr '/' ' ' | awk '{print $2}'`"
			mv $FILE_PATH $USER_IMAGES_PATH/$IMAGE_ID.$ext
		done

		see_other images

		;;
	GET)
		export _TITLE="`_ "Upload image"`"
		export _FILES="`_ Files`"
		export _SUBMIT="`_ Submit`"

		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
