#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh

Image() {
	cat <<!
<img height="128" class="ofc s_k256 b0" src="http://$HTTP_HOST/img/$REMOTE_USER/small-$1" />
!
}

Images() {
	while read line; do
		Image $line
	done
}

ls_images() {
	ls $ROOT/htdocs/img/$REMOTE_USER | sed '/^small-.*$/d'
}

case "$REQUEST_METHOD" in
	GET)
		export _TITLE="`_ Images`"
		export IMAGES="`ls_images | Images | fw`"
		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac

