#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh

case "$REQUEST_METHOD" in
	GET)
		export _TITLE="tty.pt"
		export _POEM="`_ "Programmer's poem"`"
		export _NEVERDARK="`_ "Never Dark"`"
		export _SHOPS="`_ "Shops"`"
		export _SEM="`_ "Shared Expenses Manager"`"
		export _TERMINAL="`_ "Terminal"`"
		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
