#!/bin/sh

. $DOCUMENT_ROOT/lib/optional-auth.sh
. $DOCUMENT_ROOT/lib/common.sh

case "$REQUEST_METHOD" in
	GET)
		export _TITLE="tty.pt"
		export _POEMS="`_ Poems`"
		export _NEVERDARK="`_ "Never Dark"`"
		export _SCHOOLS="`_ "Schools"`"
		export _SHOPS="`_ "Shops"`"
		export _SEM="`_ "Shared Expenses Manager"`"
		export _SOURCE_CODE="`_ "Source Code"`"
		export _TERMINAL="`_ "Terminal"`"
		export _COMMANDS="`_ "Commands"`"
		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
