#!/bin/ksh

. $ROOT/lib/common.sh

error() {
	echo 'Status: 303 See Other'
	echo "Location: login?error=$1"
	echo
	exit
}

case "$REQUEST_METHOD" in
	POST)
		hash="`grep "^$username:" $ROOT/.htpasswd | awk 'BEGIN{FS=":"} {print $2}'`"
		[[ ! -z $hash ]] || error nouser
		if crypt_checkpass "$password" "$hash"; then
			error unauthorized
		fi
		[[ ! -f $ROOT/users/$username/rcode ]] || error notactive
		TOKEN="`rand_str_1`"
		#[[ -d $ROOT/sessions ]] || mkdir $ROOT/sessions
		echo $username > $ROOT/sessions/$TOKEN
		echo 'Status: 303 See Other'
		echo "Set-Cookie: QSESSION=$TOKEN; SameSite=Lax"
		echo "Location: /e/user"
		#echo "Location: http://$username:$password@$HTTP_HOST/e/user"
		echo
		;;
	GET)
		export _TITLE="`_ Login`"
		export _ANONYMOUS_LOGIN="`_ Login` - `_ Anonymous`"
		export _REGISTER="`_ "Register"`"
		export _USERNAME="`_ "Username"`"
		export _PASSWORD="`_ "Password"`"
		export _SUBMIT="`_ "Submit"`"

		case "$error" in
			nouser) ERROR="`_ "No such user"`" ;;
			notactive) ERROR="`_ "The account was not activated"`";;
			unauthorized) ERROR="`_ "Invalid credentials"`"
		esac

		if [[ ! -z "$ERROR" ]]; then
			ERROR="<p class=\"c9\">$ERROR</p>"
		fi

		export ERROR

		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
