#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/shop.sh
. $ROOT/lib/order.sh

AccountInfo() {
	ACCOUNT_IBAN="`zcat $ROOT/users/$SHOP_OWNER/iban`"

	if [[ -z "$ACCOUNT_IBAN" ]]; then
		return
	fi

	cat <<!
<div>
	<div>`_ "Account IBAN"`</div>
	<div>$ACCOUNT_IBAN</div>
</div>
!
}

MBWayInfo() {
	PHONE_NUMBER="`zcat $ROOT/users/$SHOP_OWNER/phone_number`"

	if [[ -z $PHONE_NUMBER ]]; then
		return
	fi

	cat <<!
<div>
	<span>`_ "Phone number"` (MBWay): </span>
	<a href="tel:$PHONE_NUMBER">$PHONE_NUMBER</a>
</div>
!
}

TransferData() {
	OWNER_PATH=$ROOT/users/$SHOP_OWNER
	OWNER_EMAIL="`cat $OWNER_PATH/email`"
	cat <<!
<div>`_ "Please refer to the order number in the credit description."` (#$order_id)</div>
<div>`_ "You can send an e-mail to"` <a href="mailto:$OWNER_EMAIL">$OWNER_EMAIL</a> `_ "to speed up shipment."`</div>
`AccountInfo`
`MBWayInfo`
!
}

AddressInfo() {
	if [[ "$ORDER_STATE_TEXT" != "Pending_shipment" ]] \
		|| [[ "$REMOTE_USER" != "$SHOP_OWNER" ]]; then
		return;
	fi

	cat <<!
<pre>
`cat $ORDER_PATH/address_line_1`
`cat $ORDER_PATH/address_line_2`
`cat $ORDER_PATH/zip`
</pre>

!
}

if [[ -z "$shop_id" ]] || [[ ! -d "$SHOP_PATH" ]]; then
	Fatal 404 Shop not found
fi

SHOP_OWNER="`cat $SHOP_PATH/.owner`"
DF_USER=$SHOP_OWNER

case "$REQUEST_METHOD" in
	POST)
		if [[ -z "$order_id" ]]; then
			if [[ -z "`zcat $CART_PATH`" ]]; then
				Fatal 404 Cart not found
			fi

			if [[ -z "`zcat $USER_PATH/address_line_1`" ]] \
				|| [[ -z "`zcat $USER_PATH/address_line_2`" ]] \
				|| [[ -z "`zcat $USER_PATH/zip`" ]]; then
				Fatal 400 Invalid shipping address 
			fi

			ORDERS_PATH=$SHOP_PATH/.orders
			ORDER_ID_PATH=$SHOP_PATH/.orders/.count
			ORDER_ID="`counter_inc $ORDER_ID_PATH`"
			ORDER_PATH=$SHOP_PATH/.orders/$ORDER_ID

			fmkdir $ORDERS_PATH
			fmkdir $ORDER_PATH
			fwrite $ORDER_PATH/raw cat $CART_PATH
			fwrite $ORDER_PATH/owner echo $REMOTE_USER
			fwrite $ORDER_PATH/state echo Pending_payment
			fwrite $ORDER_PATH/address_line_1 cat $USER_PATH/address_line_1
			fwrite $ORDER_PATH/address_line_2 cat $USER_PATH/address_line_2
			fwrite $ORDER_PATH/zip cat $USER_PATH/zip

			cat $ORDER_PATH/raw | while read product_id quantity; do
				counter_dec $SHOP_PATH/$product_id/stock $quantity
			done >/tmp/null

			rm $CART_PATH # TODO also remove unneeded directories?

			see_other order ?shop_id=$shop_id\&order_id=$ORDER_ID
		else
			ORDER_PATH=$SHOP_PATH/.orders/$order_id

			if [[ "$SHOP_OWNER" != "$REMOTE_USER" ]]; then
				Fatal 401 "You can not do that"
			fi

			ORDER_STATE_TEXT="`cat $ORDER_PATH/state`"
			case "$ORDER_STATE_TEXT" in
				Pending_payment)
					ORDER_STATE_TEXT=Pending_shipment
					;;
				Pending_shipment)
					ORDER_STATE_TEXT=Shipped
					;;
				Shipped)
					ORDER_STATE_TEXT=Delivered
					;;
				Delivered)
					rm -rf $ORDER_PATH
					see_other orders ?shop_id=$shop_id
					exit
					;;
			esac

			fwrite $ORDER_PATH/state echo $ORDER_STATE_TEXT

			case "$return" in
				order)
					see_other order ?shop_id=$shop_id\&order_id=$order_id
					;;
				orders)
					see_other orders ?shop_id=$shop_id
					;;
			esac
		fi

		;;

	GET)
		ORDER_PATH=$SHOP_PATH/.orders/$order_id
		if [[ -z "$order_id" ]] || [[ ! -d "$ORDER_PATH" ]]; then
			Fatal 404 Order not found
		fi

		SHOP_OWNER="`cat $SHOP_PATH/.owner`"
		ORDER_OWNER="`cat $ORDER_PATH/owner`"

		if [[ "$REMOTE_USER" != "$ORDER_OWNER" ]] \
			&& [[ "$REMOTE_USER" != "$SHOP_OWNER" ]]; then

			Fatal 401 "You can not do that"
		fi

		export order_id

		export _TITLE="`_ $shop_id` - `_ Order` #$order_id"

		TOTAL_EXP="`process_cart $ORDER_PATH/raw`"
		export TOTAL="`echo "$TOTAL_EXP" | bc -l`"
		export PRODUCTS="`ProductsFromCart  $ORDER_PATH/raw`"
		ORDER_STATE_TEXT="`cat $ORDER_PATH/state`"
		export ADDRESS_INFO="`AddressInfo`"
		export ORDER_STATE="`OrderState -rorder "$ORDER_STATE_TEXT" $order_id`"
		if [[ "$REMOTE_USER" == "$ORDER_OWNER" ]]; then
			case "$ORDER_STATE_TEXT" in
				Pending_payment)
					TRANSFER_DATA=`TransferData`
					export TRANSFER_DATA
					;;
			esac
		fi
		NormalCat ?shop_id=$shop_id
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac


