#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh

case "$REQUEST_METHOD" in
	POST)
		poem_id="`cat $ROOT/tmp/mpfd/poem_id`"

		if invalid_id $poem_id; then
			Fatal 400 Not a valid ID
		fi

		POEM_PATH="$ROOT/poems/$poem_id"

		fmkdir $POEM_PATH
		echo $REMOTE_USER | fwrite $POEM_PATH/.owner

		mpfd-ls | while read FILE_PATH filename ; do
			file_lang="`echo $filename | sed 's/\.[^.]*$//'`"
			if invalid_lang "$file_lang"; then
				Fatal 400 Not a valid locale
			fi
			fbytes $FILE_PATH
			cat $FILE_PATH | cslash > $POEM_PATH/$file_lang.html
			rm $FILE_PATH
		done

		if [[ ! -f $POEM_PATH/$lang.html ]]; then
			rm -rf $POEM_PATH
			Fatal 400 You must submit a poem in your language
		fi

		see_other poem ?poem_id=$poem_id
		;;

	GET)
		export _TITLE="`_ "Add poem"`"
		export _POEM_ID="`_ "Poem ID"`"
		export _FILES="`_ Files`"
		export _ADD_POEM_NOTE="`_ add_poem_note` $lang.html"
		export _SUBMIT="`_ Submit`"

		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac


