#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh

poems_list() {
	ls $ROOT/poems | while read line; do
		if [[ ! -f "$ROOT/poems/$line/.hidden" ]]; then
			echo $line
		fi
	done
}

case "$REQUEST_METHOD" in
	GET)
		export _TITLE="`_ Poems`"

		if [[ ! -z "$REMOTE_USER" ]]; then
			export POEM_ADD="<a class=\"$RB\" href=\"/e/poem-add\">+</p>"
		fi

		export POEMS="`poems_list | BigButtons poem`"
		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
