#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh

case "$REQUEST_METHOD" in
	GET)
		export _TITLE="`_ Poems`"

		if [[ ! -z "$REMOTE_USER" ]]; then
			export POEM_ADD="<a class=\"$RB\" href=\"/e/poem-add\">+</p>"
		fi

		export POEMS="`ls $ROOT/poems | BigButtons poem`"
		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
