#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/shop.sh

if [[ -z "$shop_id" ]] || [[ ! -d "$SHOP_PATH" ]]; then
	Fatal 404 Shop not found
fi

case "$REQUEST_METHOD" in
	POST)
		local product_path=$SHOP_PATH/$product_id

		if [[ -z "$product_id" ]] || [[ ! -d "$product_path" ]]; then
			Fatal 404 Product not found
		fi

		SHOP_OWNER="`cat $SHOP_PATH/.owner`"

		im $SHOP_OWNER || Forbidden

		product_rm $product_id

		see_other shop ?shop_id=$shop_id
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
