#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/shop.sh

if [[ -z "$shop_id" ]] || [[ ! -d "$SHOP_PATH" ]]; then
	fatal 404 Shop not found
fi

im $SHOP_OWNER || Forbidden

js() {
	cat <<!
`cat $ROOT/js/nfiles.js`

nfiles( 'images',
	document.getElementById('images'),
	document.getElementById('submit'),
	'`_ Submit`', 'file[]', '/e/image-add', '/e/images-edit');
!
}

nfiles() {
	urldecode "$@" | sed '/^$/d' | tr -d '\r'
}

a2l() {
	while [[ $# -ge 1 ]]; do
		echo $1
		shift;
	done
}

case "$REQUEST_METHOD" in
	POST)
		PRODUCT_PATH=$SHOP_PATH/$product_id
		DF_USER=$SHOP_OWNER

		fmkdir $PRODUCT_PATH
		fwrite $PRODUCT_PATH/title urldecode $title
		fwrite $PRODUCT_PATH/description urldecode $description
		images="`nfiles $images`"
		[[ -z "$images" ]] || fwrite $PRODUCT_PATH/images a2l $images
		fwrite $PRODUCT_PATH/price echo $price

		local stock_exp="`cat $PRODUCT_PATH/stock` + $stock"
		local new_stock="`echo $stock_exp | bc`"
		fwrite $PRODUCT_PATH/stock echo $new_stock

		see_other product ?shop_id=$shop_id\&product_id=$product_id
		;;

	GET)
		export _TITLE="`_ $shop_id` - `_ "Edit product"` #$product_id"
		export __TITLE="`_ Title`"
		export _DESCRIPTION="`_ Description`"
		export _IMAGES="`_ Images`"
		export _ADD_TO_STOCK="`_ "Add to stock"`"
		export _PRICE="`_ Price`"
		export _SUBMIT="`_ Submit`"
		export JS="`js`"

		product_env $product_id
		export product_id
		export product_stock
		export product_title
		export product_description
		export product_images
		export product_price

		NormalCat ?shop_id=$shop_id
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
