#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/shop.sh

if [[ -z "$shop_id" ]] || [[ ! -d "$SHOP_PATH" ]]; then
	fatal 404 Shop not found
fi

im $SHOP_OWNER || Forbidden

case "$REQUEST_METHOD" in
	POST)
		PRODUCT_ID_PATH=$SHOP_PATH/.count
		PRODUCT_ID="`counter_inc $PRODUCT_ID_PATH`"
		PRODUCT_PATH=$SHOP_PATH/$PRODUCT_ID
		DF_USER=$SHOP_OWNER

		fmkdir $PRODUCT_PATH
		fwrite $PRODUCT_PATH/title urldecode $title
		fwrite $PRODUCT_PATH/description urldecode $description
		[[ -z "$images" ]] || fwrite $PRODUCT_PATH/images urldecode $images
		fwrite $PRODUCT_PATH/price echo $price
		fwrite $PRODUCT_PATH/stock echo $stock

		see_other shop ?shop_id=$shop_id
		;;

	GET)
		export _TITLE="`_ $shop_id` - `_ "Add product"`"
		export __TITLE="`_ Title`"
		export _DESCRIPTION="`_ Description`"
		export _IMAGES="`_ Images`"
		export _STOCK="`_ Stock`"
		export _PRICE="`_ Price`"
		export _SUBMIT="`_ Submit`"

		NormalCat ?shop_id=$shop_id
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
