#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/shop.sh

if [[ -z "$shop_id" ]] || [[ ! -d "$SHOP_PATH" ]]; then
	Fatal 404 Shop not found
fi

PRODUCT_PATH=$SHOP_PATH/$product_id

if [[ -z "$product_id" ]] || [[ ! -d "$PRODUCT_PATH" ]]; then
	Fatal 404 Product not found
fi

ProductImages() {
	while read product_image_path; do
		PImage $product_image_path | surround a "href=\"$product_image_path\""
	done
}

CartAdd() {
	if [[ $product_stock -le 0 ]]; then
		return
	fi

	cat <<!
<form action="/e/cart" method="POST">
	<button class="rs ps">`_ "Add to cart"`</button>	
	<input type="hidden" name="shop_id" value="$shop_id"></input>
	<input type="hidden" name="product_id" value="$product_id"></input>
</form>
!
}

ProductDelete() {
	cat <<!
<form action="/e/product-delete" method="POST">
	<input type="hidden" name="shop_id" value="$shop_id"></input>
	<input type="hidden" name="product_id" value="$product_id"></input>
	<button class="rs ps c1">`_ "Delete product"`</button>
</form>
!
}

case "$REQUEST_METHOD" in
	GET)

		export _TITLE="`_ $shop_id` - `_ Product` #$product_id"

		product_env $product_id
		export product_title
		export product_price
		export product_stock
		export PRODUCT_IMAGES="`echo "$product_images" | ProductImages | fw s`"
		export _STOCK="`_ Stock`"
		
		if [[ "$product_stock" != "0" ]]; then
			export ADD_TO_CART="`CartAdd $CART_PATH`"
		fi

		if im $SHOP_OWNER; then
			export DELETE_PRODUCT="`ProductDelete $product_id`"
			export EDIT_BTN="`EditBtn "/e/product-edit?shop_id=$shop_id&product_id=$product_id"`"
		fi

		NormalCat ?shop_id=$shop_id\&product_id=$product_id
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
