#!/bin/ksh

. $ROOT/lib/common.sh

error() {
	see_other register ?error=$1
	exit
}

case "$REQUEST_METHOD" in
	POST)
		username="`urldecode $username`"
		password="`urldecode $password`"
		password2="`urldecode $password2`"
		email="`urldecode $email`"

		if not_valid_password $password; then
			Fatal 400 Not a valid password
		fi

		if [[ "$password" != "$password2" ]]; then
			Fatal 400 The passwords don\'t match
		fi

		if grep -q "^$username:" $ROOT/.htpasswd; then
			Fatal 400 User already exists
		fi

		USER_DIR=$ROOT/users/$username
		DF_USER=$username
		fmkdir $USER_DIR
		fwrite $USER_DIR/email echo $email
		echo $username:$password | htpasswd -I $ROOT/.htpasswd
		rand_str="`rand_str_1`"
		fwrite $USER_DIR/rcode echo "$rand_str"
		femail -f noreply@tty.pt $email <<!
Subject: `_ "Registration on tty.pt"`

`_ "Welcome to tty.pt!"`

`_ "To confirm that this e-mail address belongs to you, go to the page at:"`
https://tty.pt/e/registration-confirm?username=$username&rcode=$rand_str

`_ "You will then be able to use your account."`

`_ "Thank you!"`
!
		see_other registration-complete
		;;
	GET)
		export _REGISTER="`_ "Register"`"
		export _USERNAME="`_ "Username"`"
		export _PASSWORD="`_ "Password"`"
		export _REPEAT_PASSWORD="`_ "Repeat password"`"
		export _EMAIL="`_ "Email"`"
		export _SUBMIT="`_ "Submit"`"
		export _LOGIN="`_ Login`"
		export _COOKIE_POLICY="`_ "Cookie policy"`"

		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
