#!/bin/ksh

. $ROOT/lib/common.sh

error() {
	see_other register ?error=$1
	exit
}

registration_email() {
}

case "$REQUEST_METHOD" in
	POST)
		if [[ "$password" == "$password2" ]];  then
			if grep -q "^$username:" $ROOT/.htpasswd; then
				error match
			fi

			USER_DIR=$ROOT/users/$username
			DF_USER=$username
			fmkdir $USER_DIR
			email="`urldecode $email`"
			fwrite $USER_DIR/email echo $email
			username="`urldecode $username`"
			echo $username:`urldecode $password` | htpasswd -I $ROOT/.htpasswd
			rand_str="`rand_str_1`"
			fwrite $USER_DIR/rcode echo "$rand_str"
			femail -f noreply@tty.pt $email <<!
Subject: `_ "Registration on tty.pt"`

`_ "Welcome to tty.pt!"`

`_ "To confirm that this e-mail address belongs to you, go to the page at:"`
https://tty.pt/e/registration-confirm?username=$username&rcode=$rand_str

`_ "You will then be able to use your account."`

`_ "Thank you!"`
!
			see_other registration-complete
		else
			error nomatch
		fi
		;;
	GET)
		export _REGISTER="`_ "Register"`"
		export _USERNAME="`_ "Username"`"
		export _PASSWORD="`_ "Password"`"
		export _REPEAT_PASSWORD="`_ "Repeat password"`"
		export _EMAIL="`_ "Email"`"
		export _SUBMIT="`_ "Submit"`"
		export _LOGIN="`_ Login`"

		case "$error" in
			nomatch)
				ERROR="`_ "Passwords don't match"`"
				;;
			match)
				ERROR="`_ "User already exists"`"
				;;
			*)
				;;
		esac

		if [[ ! -z "$ERROR" ]]; then
			ERROR="<p class=\"c9\">$ERROR</p>"
		fi

		export ERROR

		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
