#!/bin/ksh

. $DOCUMENT_ROOT/lib/optional-auth.sh
. $DOCUMENT_ROOT/lib/common.sh
. $DOCUMENT_ROOT/lib/school.sh

case "$REQUEST_METHOD" in
	GET)
		# export SCHOOL_MENU="`SchoolMenu`"
		export _TEACHERS="`_ Teachers`"
		export _STUDENTS="`_ Students`"
		export _COURSES="`_ Courses`"
		export _CLASSES="`_ Classes`"
		export school_title="`cat $SCHOOL_PATH/title`"

		NormalCat ?school_id=$school_id

		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac

