#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/sem.sh
sem_source

case "$REQUEST_METHOD" in
	GET)
		export _TITLE="`_ $sem_id`"
		export _SUBMIT="`_ Submit`"
		export _DOWNLOAD="`_ Download`"
		export _GRAPH="`_ Graph`"
		export _DEBUG="`_ Debug`"
		export _HUMAN="`_ Human`"
		export _MACHINE="`_ Machine`"
		export _PRESENT="`_ Present`"
		options=""

		export SEM_MENU="`SemMenu`"

		if [[ "$graph" == "on" ]]; then
			export graph_checked=checked
			options=$options"g"
		fi

		if [[ "$debug" == "on" ]]; then
			export debug_checked=checked
			options=$options"d"
		fi

		if [[ "$human" == "on" ]]; then
			export human_checked=checked
			options=$options"h"
		fi

		if [[ "$machine" == "on" ]]; then
			export machine_checked=checked
			options=$options"m"
		fi

		if [[ "$present" == "on" ]]; then
			export present_checked=checked
			options=$options"p"
		fi

		if [[ ! -z "$options" ]]; then
			options="-$options"
		fi

		export SEM="`$SEM $options 2>&1 < $SEM_FILE`"

		NormalCat ?sem_id=$sem_id

		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
