#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/sem.sh

pay_options() {
	if im $SEM_OWNER; then
		$SEM -p < $SEM_FILE | awk '{ print $2 }'
	else
		echo $REMOTE_USER
	fi
}

case "$REQUEST_METHOD" in
	POST)
		sem_op PAY `urldecode $ts` $id `urldecode $value` `urldecode $from` `urldecode $to` `urldecode $rest`

		;;
	GET)
		export _TITLE="`_ Pay`"
		export SEM_MENU="`SemMenu pay`"
		export NOW="`date -u +"%Y-%m-%dT%H:%M:%S"`"
		export DNOW="`date -u +"%Y-%m-%d"`T00:00:00"
		export ID_OPTIONS="`pay_options | IdOptions`"
		NormalCat ?sem_id=$sem_id

		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
