#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/sem.sh

buy_options() {
	if [[ "$REMOTE_USER" == "$SEM_OWNER" ]]; then
		$SEM -p < $SEM_FILE | awk '{ print $2 }'
	else
		echo $REMOTE_USER
	fi
}

case "$REQUEST_METHOD" in
	POST)
		sem_op BUY `urldecode $ts` $id `urldecode $value` `urldecode $rest`

		;;
	GET)
		export _TITLE="`_ Buy`"
		export SEM_MENU="`SemMenu buy`"
		export NOW="`date -u +"%Y-%m-%dT%H:%M:%S"`"
		export ID_OPTIONS="`buy_options | IdOptions`"
		NormalCat ?sem_id=$sem_id

		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
