#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/sem.sh
sem_source

case "$REQUEST_METHOD" in
	GET)
		echo Status 200: Ok
		echo Content-Type: text
		echo
		cat $SEM_FILE

		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
