#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh

case "$REQUEST_METHOD" in
	POST)
		sem_id="`cat $ROOT/tmp/mpfd/sem_id`"
		sem_id="`urldecode $sem_id`"

		if not_valid_id $sem_id; then
			Fatal 400 Not a valid ID
		fi

		SEM_PATH="$ROOT/sems/$sem_id"

		fmkdir $SEM_PATH
		fwrite $SEM_PATH/.owner echo $REMOTE_USER

		FILE_PATH=$ROOT/tmp/mpfd/file
		if [[ -f $FILE_PATH ]]; then
			fbytes $FILE_PATH
			mv $FILE_PATH $SEM_PATH/data.txt
		fi

		see_other sem ?sem_id=$sem_id
		;;

	GET)
		export _TITLE="`_ "Add sem"`"
		export _SEM_ID="`_ "Sem ID"`"
		export _SUBMIT="`_ Submit`"

		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
