#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/sem.sh

if [[ "$REMOTE_USER" != "$SEM_OWNER" ]]; then
	Unauthorized
fi

case "$REQUEST_METHOD" in
	POST)
		sem_op START `urldecode $ts` $id `urldecode $rest`

		;;
	GET)
		export _TITLE="`_ Start`"
		export SEM_MENU="`SemMenu start`"
		export NOW="`date -u +"%Y-%m-%dT%H:%M:%S"`"
		NormalCat ?sem_id=$sem_id

		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
