#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/sem.sh

stop_options() {
	if im $SEM_OWNER; then
		$SEM -p < $SEM_FILE | awk '{ print $2 }'
	else
		echo $REMOTE_USER
	fi
}

case "$REQUEST_METHOD" in
	POST)
		sem_op STOP `urldecode $ts` $id `urldecode $rest`

		;;
	GET)
		export _TITLE="`_ stop`"
		export _DATE_TIME="`_ "Date / Time"`"
		export _MORE_INFO="`_ "More information"`"
		export _SUBMIT="`_ Submit`"
		export SEM_MENU="`SemMenu stop`"
		export NOW="`date -u +"%Y-%m-%dT%H:%M:%S"`"
		export ID_OPTIONS="`stop_options | IdOptions`"
		NormalCat ?sem_id=$sem_id

		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
