#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/sem.sh

im $SEM_OWNER || Forbidden

case "$REQUEST_METHOD" in
	POST)
		sem_op START `urldecode $ts` $id `urldecode $tel` `urldecode $email` `urldecode $name`

		;;
	GET)
		export _TITLE="`_ start`"
		export _DATE_TIME="`_ "Date / Time"`"
		export _TELEPHONE="`_ Telephone`"
		export _EMAIL="`_ Email`"
		export _NAME="`_ Name`"
		export _SUBMIT="`_ Submit`"
		export SEM_MENU="`SemMenu start`"
		export NOW="`date -u +"%Y-%m-%dT%H:%M:%S"`"
		NormalCat ?sem_id=$sem_id

		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
