#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh

case "$REQUEST_METHOD" in
	GET)
		export _TITLE="`_ Sems`"
		if [[ ! -z "$REMOTE_USER" ]]; then
			export SEM_ADD="<a class=\"$RB\" href=\"/e/sem-add\">+</a>"
		fi

		export SEMS="`ls $ROOT/sems | BigButtons sem`"
		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac

