#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh

case "$REQUEST_METHOD" in
	GET)
		export _TITLE="`_ Shops`"
		if [[ ! -z "$REMOTE_USER" ]]; then
			export SHOP_ADD="<a class=\"$RB\" href=\"/e/shop-add\">+</a>"
		fi

		export SHOPS="`ls_shown $ROOT/shops | BigButtons shop`"
		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
