#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/shop.sh

lsshown() {
	 find $1 -type d -mindepth 1 -maxdepth 1 -name "[!.]*" | sed "s|$1||" | sed "s/\/$//"
}

Products() {
	local product_id
	while read product_id; do
		local card_class=""

		product_env $product_id

		if [[ "$product_stock" == "0" ]]; then
			card_class="c0"
		fi

		cat <<!
<a class="card f vs b0 fic p $card_class" href="/e/product?shop_id=$shop_id&product_id=$product_id">
	`PImage $product_image_path`
	<div class="tsl">$product_price€</div>
	<span class="tsxl">$product_title</span>
	`echo "$product_description" | csurround p`
</a>
!
	done
}

ShopButtons() {
	[[ ! -z "$REMOTE_USER" ]] || return

	cat <<!
<a class="$RB" href="/e/orders?shop_id=$shop_id">🚚</a>
<a class="$RB" href="/e/cart?shop_id=$shop_id">🛒</a>
!
}

if [[ -z "$shop_id" ]] || [[ ! -d "$SHOP_PATH" ]]; then
	Fatal 404 Shop not found
fi

case "$REQUEST_METHOD" in
	POST)
		case "$action" in
			delete)
				PRODUCT_PATH=$SHOP_PATH/$product_id
				if [[ -z "$product_id" ]] || [[ ! -d "$PRODUCT_PATH" ]]; then
					Fatal 404 Product not found
				fi

				im $SHOP_OWNER || Forbidden

				rm -rf $SHOP_PATH/$product_id

				see_other shop ?shop_id=$shop_id
				;;
			*)
				Fatal 400 Invalid action
				;;
		esac

		;;
	GET)
		export _TITLE="`_ $shop_id`"

		export PRODUCTS="`lsshown $SHOP_PATH/ | Products | fw`"
		export SHOP_BUTTONS="`ShopButtons`"
		if im $SHOP_OWNER; then
			export ADD_PRODUCT_BUTTON="<div class=\"tar\"><a class=\"tsxl round ps btn\" href=\"/e/product-add?shop_id=$shop_id\">+</a></div>"
			export EDIT_BTN="`EditBtn "/e/shop-edit?shop_id=$shop_id"`"
		fi

		NormalCat ?shop_id=$shop_id
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
