#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh

Shop() {
	SHOPNAME="$1"
	_TITLE="`_ $SHOPNAME`"
	cat <<EOF
<a class="btn tsxl" href="/e/shop?shop_id=$SHOPNAME">
	$_TITLE
</a>
EOF
}

Shops() {
	while read line; do Shop $line; done
}

case "$REQUEST_METHOD" in
	GET)
		export _TITLE="`_ Shops`"
		if [[ ! -z "$REMOTE_USER" ]]; then
			export SHOP_ADD="<a class=\"$RB\" href=\"/e/shop-add\">+</a>"
		fi

		export SHOPS="`ls $ROOT/shops | Shops`"
		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
