#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/shop.sh

lsshown() {
	 find $1 -type d -mindepth 1 -maxdepth 1 -name "[!.]*" | sed "s|$1||" | sed "s/\/$//"
}

Products() {
	local product_id
	while read product_id; do
		if [[ "`cat $SHOP_PATH/$product_id/stock`" -gt 0 ]]; then
			product_env $product_id
			cat <<!
<label class="card f vs b0 fic p">
	`PImage $product_image_path`
	<div class="tsl">$product_price€</div>
	<a class="tsxl" href="/e/product?shop_id=$shop_id&product_id=$product_id">$product_title</a>
	`echo "$product_description" | csurround p`
	<input name="delete_$product_id" type="checkbox"></input>
</label>
!
		fi
	done
}

if [[ -z "$shop_id" ]] || [[ ! -d "$SHOP_PATH" ]]; then
	Fatal 404 Shop not found
fi

case "$REQUEST_METHOD" in
	POST)
		im $SHOP_OWNER || Forbidden

		lsshown $SHOP_PATH/ | while read product_id; do
			local qname=delete_$product_id
			eval echo $product_id \$$qname
		done | while read product_id state; do
			[[ "$state" != "on" ]] || rm -rf $SHOP_PATH/$product_id
		done

		see_other shop ?shop_id=$shop_id

		;;
	GET)
		export _TITLE="`_ $shop_id` - `_ "Edit shop"`"
		export _DELETE_PRODUCTS="`_ "Delete products"`"

		export PRODUCTS="`lsshown $SHOP_PATH/ | Products | fw`"
		SHOP_OWNER="`cat $SHOP_PATH/.owner`"
		export SHOP_BUTTONS="`ShopButtons`"
		if im $SHOP_OWNER; then
			export ADD_PRODUCT_BUTTON="<div class=\"tar\"><a class=\"tsxl round ps btn\" href=\"/e/product-add?shop_id=$shop_id\">+</a></div>"
			export EDIT_BTN="<a class=\"$RB\" href=\"/e/shop-edit?shop_id=$shop_id\">🖉</a>"
		fi

		NormalCat ?shop_id=$shop_id
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
