#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/school.sh

im $SCHOOL_OWNER $student_id || Forbidden

case "$REQUEST_METHOD" in
	POST)
		if invalid_id $student_id; then
			Fatal 400 Not a valid ID
		fi

		SCHOOL_PATH="$ROOT/schools/$school_id"
		STUDENT_PATH="$SCHOOL_PATH/students/$student_id"

		fwrite $STUDENT_PATH/name urldecode $name
		fwrite $STUDENT_PATH/dob urldecode $dob

		see_other student ?school_id=$school_id\&student_id=$student_id
		;;

	GET)
		STUDENT_PATH=$SCHOOL_PATH/students/$student_id

		export student_id
		export _EDIT="`_ Edit`"
		export _STUDENT="`_ Student`"
		export _NAME="`_ Name`"
		export name="`cat $STUDENT_PATH/name`"
		export _DOB="`_ "Date of birth"`"
		export dob="`cat $STUDENT_PATH/dob`"
		export _SUBMIT="`_ Submit`"
		export EDIT_BTN="<a class=\"$RB\" href=\"/e/student-edit?school_id=$school_id&student_id=$student_id\"\">🖉</a>"

		NormalCat ?school_id=$school_id\&student_id=$student_id

		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
