#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/school.sh

im $SCHOOL_OWNER $student_id || Forbidden

case "$REQUEST_METHOD" in
	POST)
		if invalid_s courses $course_id; then
			Fatal 400 That course does not exist
		fi

		STUDENT_PATH="$SCHOOL_PATH/students/$student_id"

		if grep -q "$course_id_id" "$STUDENT_PATH/courses"; then
			Fatal 400 That course is already assigned to this student
		fi

		echo $course_id | fappend "$STUDENT_PATH/courses"

		see_other student ?school_id=$school_id\&student_id=$student_id
		;;

	GET)
		export _TITLE="`_ "Assign course to student"`"
		export _CLASS_ID="`_ "Course ID"`"
		export _SUBMIT="`_ Submit`"
		export student_id

		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
