#!/bin/ksh

. $DOCUMENT_ROOT/lib/optional-auth.sh
. $DOCUMENT_ROOT/lib/common.sh
. $DOCUMENT_ROOT/lib/school.sh

invalid_s students $student_id && Fatal 400 Invalid student

STUDENT_PATH=$SCHOOL_PATH/students/$student_id

Courses() {
	{
		cat $STUDENT_PATH/courses | SmallButtons course \&school_id=$school_id
		if im $SCHOOL_OWNER $student_id; then
			echo "<a class=\"$RBS\" href=\"/e/student-course-associate?school_id=$school_id&student_id=$student_id\">+</a>"
		fi
	} | cond || {
		echo "<h2>`_ Courses`</h2>"
		cat $contents | fw 8
	}
}

Grades() {
	cat $STUDENT_PATH/grades | while read class_id grade; do
		cat <<!
<div class="ps c0 _">
	<a href="/e/class?school_id=$school_id&class_id=$class_id">$class_id</a>
	<span>$grade</span>
</div>
!
	done | cond || {
		echo "<h2>`_ Grades`</h2>"
		cat $contents | fw 8
	}
}

RNField() {
	Field "`_ "Registration Number"`" "`cat $STUDENT_PATH/required_number`"
}

NameField() {
	Field "`_ Name`" "`cat $STUDENT_PATH/name`"
}

DobField() {
	Field "`_ "Date of birth"`" "`cat $STUDENT_PATH/dob`"
}

case "$REQUEST_METHOD" in
	GET)
		export student_id
		export _STUDENT="`_ Student`"
		export COURSES="`Courses`"
		export RN="`RNField`"
		export NAME="`NameField`"
		export DOB="`DobField`"
		export GRADES="`Grades`"

		if im $SCHOOL_OWNER $student_id; then
			export EDIT_BTN="`EditBtn "/e/student-edit?school_id=$school_id&student_id=$student_id"`"
		fi

		NormalCat ?school_id=$school_id\&student_id=$student_id

		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
