#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/school.sh

case "$REQUEST_METHOD" in
	GET)
		export _TITLE="`_ Students`"

		if im $SCHOOL_OWNER; then
			export STUDENT_ADD="<a class=\"$RB\" href=\"/e/student-add?school_id=$school_id\">+</a>"
		fi

		export STUDENTS="`ls $SCHOOL_PATH/students | BigButtons student \&school_id=$school_id`"
		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
