#!/bin/ksh

. $DOCUMENT_ROOT/lib/auth.sh
. $DOCUMENT_ROOT/lib/common.sh
. $DOCUMENT_ROOT/lib/school.sh

im $SCHOOL_OWNER || Forbidden

case "$REQUEST_METHOD" in
	POST)
		if invalid_id $student_id; then
			Fatal 400 Not a valid ID
		fi

		STUDENT_PATH="$SCHOOL_PATH/students/$student_id"

		fmkdir $STUDENT_PATH
		urldecode $name | fwrite $STUDENT_PATH/name
		urldecode $dob | fwrite $STUDENT_PATH/dob
		counter_inc $SCHOOL_PATH/students/.count | fwrite $STUDENT_PATH/required_number

		see_other student ?school_id=$school_id\&student_id=$student_id
		;;

	GET)
		export _TITLE="`_ "Add student to school"`"
		export _STUDENT_ID="`_ "Student ID"`"
		export _NAME="`_ Name`"
		export _DOB="`_ "Date of birth"`"
		export _SUBMIT="`_ Submit`"

		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
