#!/bin/ksh

. $DOCUMENT_ROOT/lib/auth.sh
. $DOCUMENT_ROOT/lib/common.sh
. $DOCUMENT_ROOT/lib/school.sh

im $SCHOOL_OWNER $student_id || Forbidden

STUDENT_PATH=$SCHOOL_PATH/students/$student_id

case "$REQUEST_METHOD" in
	POST)
		if invalid_id $student_id; then
			Fatal 400 Not a valid ID
		fi

		urldecode $name | fwrite $STUDENT_PATH/name
		urldecode $dob | fwrite $STUDENT_PATH/dob

		see_other student ?school_id=$school_id\&student_id=$student_id
		;;

	GET)
		export student_id
		export _EDIT="`_ Edit`"
		export _STUDENT="`_ Student`"
		export _NAME="`_ Name`"
		export name="`cat $STUDENT_PATH/name`"
		export _DOB="`_ "Date of birth"`"
		export dob="`cat $STUDENT_PATH/dob`"
		export _SUBMIT="`_ Submit`"

		if im $SCHOOL_OWNER $student_id; then
			export EDIT_BTN="`EditBtn "/e/student-edit?school_id=$school_id&student_id=$student_id"`"
		fi

		NormalCat ?school_id=$school_id\&student_id=$student_id

		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
