#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/school.sh

Courses() {
	STUDENT_PATH=$SCHOOL_PATH/students/$student_id
	{
		cat $STUDENT_PATH/courses | SmallButtons course \&school_id=$school_id
		if [[ "$REMOTE_USER" == "$SCHOOL_OWNER" ]] \
			|| [[ "$REMOTE_USER" == "$student_id" ]]; then
			echo "<a class=\"$RBS\" href=\"/e/student-course-associate?school_id=$school_id&student_id=$student_id\">+</a>"
		fi
	} | FWS
}

case "$REQUEST_METHOD" in
	GET)
		export student_id
		export _STUDENT="`_ Student`"
		export _COURSES="`_ Courses`"
		export COURSES="`Courses`"

		NormalCat ?school_id=$school_id\&student_id=$student_id

		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
