#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/school.sh

case "$REQUEST_METHOD" in
	POST)
		school_id="`urldecode $school_id`"
		student_id="`urldecode $student_id`"

		if invalid_id $student_id; then
			Fatal 400 Not a valid ID
		fi

		SCHOOL_PATH="$ROOT/schools/$school_id"
		STUDENT_PATH="$SCHOOL_PATH/students/$student_id"

		fmkdir $STUDENT_PATH

		see_other student ?school_id=$school_id\&student_id=$student_id
		;;

	GET)
		export _TITLE="`_ "Add student to school"`"
		export _STUDENT_ID="`_ "Student ID"`"
		export _SUBMIT="`_ Submit`"

		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
