#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/school.sh

ls_teachers() {
	ls $SCHOOL_PATH/classes | while read line; do
		cat $SCHOOL_PATH/classes/$line/.teacher
	done
}

case "$REQUEST_METHOD" in
	GET)
		export _TITLE="`_ Teachers`"
		export TEACHERS="`ls_teachers | BigButtons teacher \&school_id=$school_id`"
		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
