#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/school.sh

teacher_things() {
	for_each_in "$SCHOOL_PATH/$1" .teacher "$teacher_id"
}

Classes() {
	teacher_things classes | SmallButtons class \&school_id=$school_id | FWS
}

Courses() {
	teacher_things courses | SmallButtons course \&school_id=$school_id | FWS
}

salary_exp() {
	pay_per_class=750
	pay_per_course=2500

	teacher_things classes | while read ignored; do
		echo $pay_per_class
	done | sum_lines_exp

	echo -n " + "

	teacher_things courses | while read ignored; do
		echo $pay_per_course
	done | sum_lines_exp
}

case "$REQUEST_METHOD" in
	GET)
		export teacher_id
		export _TEACHER="`_ Teacher`"
		export _CLASSES="`_ Classes`"
		export CLASSES="`Classes`"
		export _REGENT="`_ Regent`"
		export _COURSES="`_ Courses`"
		export COURSES="`Courses`"
		TEACHER_PATH=$SCHOOL_PATH/teachers/$teacher_id
		export _DOB="`_ "Date of birth"`"
		export dob="`cat $TEACHER_PATH/dob`"
		export _NAME="`_ Name`"
		export name="`cat $TEACHER_PATH/name`"
		export _SALARY="`_ Salary`"
		salary_exp="`salary_exp`"
		export salary="`echo "$salary_exp" | bc`€"

		if im $SCHOOL_OWNER $teacher_id; then
			export EDIT_BTN="<a class=\"$RB\" href=\"/e/teacher-edit?school_id=$school_id&teacher_id=$teacher_id\"\">🖉</a>"
		fi

		NormalCat ?school_id=$school_id\&teacher_id=$teacher_id

		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
