#!/bin/ksh

. $DOCUMENT_ROOT/lib/auth.sh
. $DOCUMENT_ROOT/lib/common.sh
. $DOCUMENT_ROOT/lib/school.sh

im $SCHOOL_OWNER || Forbidden

case "$REQUEST_METHOD" in
	POST)
		if invalid_id $teacher_id; then
			Fatal 400 Not a valid ID
		fi

		TEACHER_PATH="$SCHOOL_PATH/students/$teacher_id"

		fmkdir $TEACHER_PATH
		urldecode $name | fwrite $TEACHER_PATH/name
		urldecode $dob | fwrite $TEACHER_PATH/dob

		see_other student ?school_id=$school_id\&student_id=$student_id
		;;

	GET)
		export _TITLE="`_ "Add teacher to school"`"
		export _TEACHER_ID="`_ "Teacher ID"`"
		export _NAME="`_ Name`"
		export _DOB="`_ "Date of birth"`"
		export _SUBMIT="`_ Submit`"

		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
