#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh
. $ROOT/lib/school.sh

teacher_things() {
	for_each_in "$SCHOOL_PATH/$1" .teacher "$teacher_id"
}

Classes() {
	teacher_things classes | SmallButtons class \&school_id=$school_id | FWS
}

Courses() {
	teacher_things courses | SmallButtons course \&school_id=$school_id | FWS
}

case "$REQUEST_METHOD" in
	GET)
		export teacher_id
		export _TEACHER="`_ Teacher`"
		export _CLASSES="`_ Classes`"
		export CLASSES="`Classes`"
		export _REGENT="`_ Regent`"
		export _COURSES="`_ Courses`"
		export COURSES="`Courses`"

		NormalCat ?school_id=$school_id\&teacher_id=$teacher_id

		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
