#!/bin/ksh

. $DOCUMENT_ROOT/lib/auth.sh
. $DOCUMENT_ROOT/lib/common.sh
. $DOCUMENT_ROOT/lib/school.sh

im $SCHOOL_OWNER $teacher_id || Forbidden

TEACHER_PATH=$SCHOOL_PATH/teachers/$teacher_id

case "$REQUEST_METHOD" in
	POST)
		if invalid_id $teacher_id; then
			Fatal 400 Not a valid ID
		fi

		urldecode $name | fwrite $TEACHER_PATH/name
		urldecode $dob | fwrite $TEACHER_PATH/dob

		see_other teacher ?school_id=$school_id\&teacher_id=$teacher_id
		;;

	GET)
		TEACHER_PATH=$SCHOOL_PATH/teachers/$teacher_id

		export teacher_id
		export _EDIT="`_ Edit`"
		export _TEACHER="`_ Teacher`"
		export _NAME="`_ Name`"
		export name="`cat $TEACHER_PATH/name`"
		export _DOB="`_ "Date of birth"`"
		export dob="`cat $TEACHER_PATH/dob`"
		export _SUBMIT="`_ Submit`"

		if im $SCHOOL_OWNER $teacher_id; then
			export EDIT_BTN="`EditBtn "/e/teacher-edit?school_id=$school_id&teacher_id=$teacher_id"`"
		fi

		NormalCat ?school_id=$school_id\&teacher_id=$teacher_id

		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
