#!/bin/ksh

. $ROOT/lib/auth.sh
. $ROOT/lib/common.sh

USER_PATH="$ROOT/users/$REMOTE_USER"
WHISPER_PATH="$USER_PATH/.whisper"

case "$REQUEST_METHOD" in
	POST)
		cmd="`urldecode $cmd`"
		echo "$REMOTE_USER$ $cmd" >> $WHISPER_PATH

		case "$cmd" in
			help) 
				echo Welcome to the terminal
				echo Beware - the values might not be correct
				echo commands: df quota whisper
				;;
			df)
				df
				;;
			quota)
				echo "`df_total`/`free_space`"
				;;
			whisper*)
				set -- $CMD
				shift
				username=$1
				shift
				message=$@

				[[ -d $ROOT/users/$username ]] || Fatal 400 No such user

				DF_USER=$username
				fappend $ROOT/users/$username/.whisper \
					echo "$REMOTE_USER": "$message"
				echo "Sent whisper."
				;;
			*)
				;;
		esac >> $WHISPER_PATH

		;;
	GET)
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		exit
		;;
esac

export _TITLE="`_ "Terminal"`"

NormalCat
