#!/bin/ksh

. $ROOT/lib/common.sh

case "$REQUEST_METHOD" in
	GET)
		case "$k" in
			1)
				echo 'Status: 303 See Other'
				echo "Location: https://tty.pt/e/register"
				echo
				;;
		esac
		see_other index
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac

