#!/bin/ksh

. $ROOT/lib/common.sh

case "$REQUEST_METHOD" in
	GET)
		case "$k" in
			0)
				echo 'Status: 303 See Other'
				echo "Location: http://$HTTP_HOST/e/poem?poem_id=programmers_poem"
				echo
				;;
			1)
				echo 'Status: 303 See Other'
				echo "Location: http://$HTTP_HOST/e/shop?shop_id=loja_dos_sonhos"
				echo
				;;
		esac
		see_other index
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac

