#!/bin/ksh

. $ROOT/lib/optional-auth.sh
. $ROOT/lib/common.sh

USER_PATH=$ROOT/users/$REMOTE_USER

Field() {
	cat | cond || {
		cat <<!
<div class="vxs">
	<div class="tsxs">$1</div>
	<pre class="cf15">`cat $contents`</pre>
</div>
!
	}
}

Address() {
	Field "$_ADDRESS" <<!
`zcat $USER_PATH/address_line_1`
`zcat $USER_PATH/address_line_2`
`zcat $USER_PATH/zip`
!
}

PhoneNumber() {
	if [[ ! -f "$USER_PATH/phone_number" ]]; then
		return
	fi

	local label="`_ "Phone number"`"
	local value="`cat $USER_PATH/phone_number`"

	cat <<!
<div class="vxs">
	<div class="tsxs">$label</div>
	<a href="tel:$value" class="ts cf15">$value</a>
</div>
!

}

AccountInfo() {
	if [[ ! -f "$USER_PATH/iban" ]] || [[ ! -f "$USER_PATH/bicswift" ]]; then
		return
	fi

	local label="`_ "Account information"`"
	local value="`cat $USER_PATH/phone_number`"

	cat <<!
<div class="vxs tss">
	<div class="tsxs">$label</div>
	<div class="_xs">
		<span class="tsxs">`_ IBAN`</span>
		<span class="cf15">`cat $USER_PATH/iban`</span>
	</div>
	<div class="_xs">
		<span class="tsxs">`_ BICSWIFT`</span>
		<span class="cf15">`cat $USER_PATH/bicswift`</span>
	</div>
</div>
!

}

case "$REQUEST_METHOD" in
	GET)
		if [[ -z "$user_id" ]] || im $user_id; then
			export EDIT_BTN="`EditBtn "/e/user-edit?user_id=$user_id"`"
		fi

		export _TITLE="`_ User` - $REMOTE_USER"

		_NAME="`_ Name`"
		export NAME="`zcat $USER_PATH/name | Field "$_NAME"`"

		export ADDRESS="`Address`"

		export PHONE_NUMBER="`PhoneNumber`"

		export ACCOUNT_INFO="`AccountInfo`"

		export _LOGOUT="`_ Logout`"
		export _SUBMIT="`_ Submit`"

		export iban="`zcat $USER_PATH/iban`"
		export bicswift="`zcat $USER_PATH/bicswift`"

		NormalCat
		;;
	*)
		echo "Status: 405 Method Not Allowed"
		echo
		;;
esac
