#!/bin/sh

iid=$1
PRODUCT_PATH=$SHOP_PATH/$iid

shift
case "$1" in
	delete) shift; . ./delete ; exit 0 ;;
	edit) shift; . ./edit ; exit 0 ;;
esac

ProductImages() {
	while read product_image_path; do
		PImage $product_image_path | surround a "href=\"$product_image_path\""
	done
}

CartAdd() {
	if test $product_stock -le 0; then
		return
	fi

	cat <<!
<form action="/shop/$shop_id/cart" method="POST">
<button class="rs ps">`_ "Add to cart"`</button>
<input type="hidden" name="shop_id" value="$shop_id"></input>
<input type="hidden" name="iid" value="$iid"></input>
</form>
!
}

ProductDelete() {
	cat <<!
<form action="/shop/$shop_id/$iid/delete" method="POST" class="f">
<input type="hidden" name="shop_id" value="$shop_id"></input>
<input type="hidden" name="iid" value="$iid"></input>
<button class="rs ps c1">`_ "Delete product"`</button>
</form>
!
}

product_env $iid

if test "$product_stock" != "0"; then
	add_to_cart="`CartAdd $CART_PATH`"
fi

if im $OWNER; then
	delete_product="`ProductDelete $iid`"
fi

fun() {
	if im $OWNER; then
		EditBtn
	fi
}

content() {
	cat <<!
<div class="f fw h8 v8 fic">`echo "$product_images" | ProductImages | fw 8`</div>
<span class="tsxl">$product_title</span>
<div class="tsl">$product_price€</div>
<div>`_ Stock`: $product_stock</div>
$add_to_cart
$delete_product
!
}

_TITLE="`_ $shop_id` - `_ Product` #$iid"

SubIndex
NotAllowed
