#!/bin/sh

order_id=$1

AccountInfo() {
	ACCOUNT_IBAN="`zcat $ROOT/users/$OWNER/iban`"

	if test -z "$ACCOUNT_IBAN"; then
		return
	fi

	cat <<!
<div>
	<div>`_ "Account IBAN"`</div>
	<div>$ACCOUNT_IBAN</div>
</div>
!
}

MBWayInfo() {
	PHONE_NUMBER="`zcat $ROOT/users/$OWNER/phone_number`"

	if test -z $PHONE_NUMBER; then
		return
	fi

	cat <<!
<div>
	<span>`_ "Phone number"` (MBWay): </span>
	<a href="tel:$PHONE_NUMBER">$PHONE_NUMBER</a>
</div>
!
}

TransferData() {
	OWNER_PATH=$ROOT/users/$OWNER
	OWNER_EMAIL="`cat $OWNER_PATH/email`"
	cat <<!
<div>`_ "Please refer to the order number in the credit description."` (#$order_id)</div>
<div>`_ "You can send an e-mail to"` <a href="mailto:$OWNER_EMAIL">$OWNER_EMAIL</a> `_ "to speed up shipment."`</div>
`AccountInfo`
`MBWayInfo`
!
}

AddressInfo() {
	if test "$ORDER_STATE_TEXT" != "Pending_shipment" \
		|| test "$REMOTE_USER" != "$OWNER"; then
		return;
	fi

	cat <<!
<pre>
`cat $ORDER_PATH/address_line_1`
`cat $ORDER_PATH/address_line_2`
`cat $ORDER_PATH/zip`
</pre>

!
}

Products() {
	local product_id
	while read product_id quantity; do
		product_env $product_id
		cat <<!
<a class="card f v8 b0 fic p" href="/shop/$shop_id/$product_id">
	`PImage $product_image_path`
	<div class="tsxl">$product_title</div>
	`echo "$product_description" | csurround p`
	<div class="tsl">$quantity x $product_price€</div>
</a>
!
	done
}

if test -z "$shop_id" || test ! -d "$SHOP_PATH"; then
	Fatal 404 Shop not found
fi

DF_USER=$OWNER

case "$REQUEST_METHOD" in
	POST) ;;
	GET)
		ORDER_PATH=$SHOP_PATH/.orders/$order_id
		if test -z "$order_id" || test ! -d "$ORDER_PATH"; then
			Fatal 404 Order not found
		fi

		ORDER_OWNER="`cat $ORDER_PATH/owner`"

		im $ORDER_OWNER $OWNER || Forbidden

		export order_id

		export _TITLE="`_ $shop_id` - `_ Order` #$order_id"

		TOTAL_EXP="`process_cart $ORDER_PATH/raw`"
		export TOTAL="`echo "$TOTAL_EXP" | bc -l`"
		export PRODUCTS="`cat $ORDER_PATH/raw | Products`"
		ORDER_STATE_TEXT="`cat $ORDER_PATH/state`"
		export ADDRESS_INFO="`AddressInfo`"
		export ORDER_STATE="`OrderState order "$ORDER_STATE_TEXT" $order_id`"
		if im $ORDER_OWNER; then
			case "$ORDER_STATE_TEXT" in
				Pending_payment)
					TRANSFER_DATA=`TransferData`
					export TRANSFER_DATA
					;;
			esac
		fi
		Normal 200 order/$order_id
		Cat sub-index
		;;
	*) NotAllowed ;;
esac

ORDER_PATH=$SHOP_PATH/.orders/$order_id

im $OWNER || Forbidden

ORDER_STATE_TEXT="`cat $ORDER_PATH/state`"
case "$ORDER_STATE_TEXT" in
	Pending_payment)
		ORDER_STATE_TEXT=Pending_shipment
		;;
	Pending_shipment)
		ORDER_STATE_TEXT=Shipped
		;;
	Shipped)
		ORDER_STATE_TEXT=Delivered
		;;
	Delivered)
		rm -rf $ORDER_PATH
		_see_other /shop/$shop_id/order
		exit
		;;
esac

echo $ORDER_STATE_TEXT | fwrite $ORDER_PATH/state

case "$return" in
	order)
		_see_other /shop/$shop_id/order/$order_id
		;;
	orders)
		_see_other /shop/$shop_id/order
		;;
esac
