#!/bin/sh

set -- `echo $DOCUMENT_URI | tr '/' ' '`
PUSER=$1
HOME=$DOCUMENT_ROOT/home/$PUSER
shift
echo USER $PUSER >&2

case "$1" in
	"") ;;
	*)
		typ=$1
		shift
		cd $HOME/.items/$typ
		Normal 200 $typ
		SubIndex $typ $@
		exit 0
		;;
esac

_TITLE="`_ User` - $PUSER"

forks="$DOCUMENT_ROOT/home/$PUSER/.items"

if test -d $forks; then
	cat <<!
<h3>`_ Forks`</h3>
`ls $forks | \
while read type; do ls $DOCUMENT_ROOT/home/$PUSER/.items/$type | while read item; do
	echo "<a href='/$PUSER/$type/$item'>$type/$item</a>"
done; done`
<hr />
!
fi

cat <<!
<div class="tac tsxl f">
	<a class="btn" href="~$PUSER">`_ Page`</a>
</div>

<div class="tac tsxl f">
	<a class="btn" href="logout">`_ Logout`</a>
</div>
!
