#!/bin/sh

. $ROOT/lib/order.sh

if test ! -z "$1"; then
	. ./sub-index $@
	exit 0
fi

Order() {
	ORDER_PATH=$SHOP_PATH/.orders/$1
	ORDER_OWNER="`cat $ORDER_PATH/owner`"
	TOTAL_EXP="`process_cart $ORDER_PATH/raw`"
	TOTAL="`echo "$TOTAL_EXP" | bc -l`"
	ORDER_STATE_TEXT="`cat $ORDER_PATH/state`"
	ORDER_STATE="`OrderState orders "$ORDER_STATE_TEXT" $1`"

	cat <<!
<a href="/shop/$shop_id/order/$1" class="b0 p v">
	<span>
		$_ORDER #$1 - $ORDER_OWNER $TOTAL€
	</span>

	$ORDER_STATE
</a>
!
}

VendorOrders() {
	ls $SHOP_PATH/.orders | while read line; do
		Order $line
	done
}

UserOrders() {
	ls $SHOP_PATH/.orders | while read line; do
		ORDER_PATH=$SHOP_PATH/.orders/$line
		ORDER_OWNER="`cat $ORDER_PATH/owner`"
		im $ORDER_OWNER && Order $line || true
	done
}

case "$REQUEST_METHOD" in
	POST) ;;
	GET)
		ORDERS_PATH=$SHOP_PATH/.orders

		export _TITLE="`_ $shop_id` - `_ Orders`"

		_ORDER="`_ Order`"

		if im $SHOP_OWNER; then
			ORDERS="`VendorOrders`"
		else
			ORDERS="`UserOrders`"
		fi

		export ORDERS="`echo "$ORDERS" | fw`"

		Normal 200 shop/$shop_id/order
		Scat template/index
		;;
	*) NotAllowed ;;
esac

if test -z "`zcat $CART_PATH`"; then
	Fatal 404 Cart not found
fi

if test -z "`zcat $USER_PATH/address_line_1`" \
	|| test -z "`zcat $USER_PATH/address_line_2`" \
	|| test -z "`zcat $USER_PATH/zip`"; then
			Fatal 400 Invalid shipping address 
fi

ORDERS_PATH=$SHOP_PATH/.orders
ORDER_ID_PATH=$SHOP_PATH/.orders/.count
ORDER_ID="`counter_inc $ORDER_ID_PATH`"
ORDER_PATH=$SHOP_PATH/.orders/$ORDER_ID

fmkdir $ORDERS_PATH
fmkdir $ORDER_PATH
cat $CART_PATH | fwrite $ORDER_PATH/raw
echo $REMOTE_USER | fwrite $ORDER_PATH/owner
echo Pending_payment | fwrite $ORDER_PATH/state
cat $USER_PATH/address_line_1 | fwrite $ORDER_PATH/address_line_1
cat $USER_PATH/address_line_2 | fwrite $ORDER_PATH/address_line_2
cat $USER_PATH/zip | fwrite $ORDER_PATH/zip

cat $ORDER_PATH/raw | while read product_id quantity; do
	counter_dec $SHOP_PATH/$product_id/stock $quantity
done >/tmp/null

rm $CART_PATH # TODO also remove unneeded directories?

_see_other order/$ORDER_ID
